services:
  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    container_name: rentdaddy-postgres
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
       interval: 5s
       timeout: 5s
       retries: 5
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
      - "2345:2345" 
    depends_on:
      postgres:
        condition: service_healthy
    container_name: rentdaddy-backend
    restart: always
    volumes:
      - ./backend:/app
      - /app/tmp
      - /app/temp
      - ./backend/tmp:/app/tmp
      - ./backend/temp:/app/temp
      - go-mod-cache:/go/pkg/mod
    env_file: .env
    networks:
        - app-network
        - documenso-rentdaddy
    #command: ["/bin/sh", "-c", "chmod +x /app/entrypoint.sh && chown root:root /app/entrypoint.sh && /app/entrypoint.sh"]
    command: ["/bin/sh", "-c", "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"]
    

  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-5173}:${FRONTEND_PORT:-5173}"
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    networks:
      - app-network
    env_file:
      - .env  # Load .env file

networks:
  app-network:
    driver: bridge
  documenso-rentdaddy:
    external: true

volumes:
  postgres_data:
  go-mod-cache:
