version: '3.8'

services:
  postgres:
    # Reuse the postgres service from main docker-compose
    extends:
      file: docker-compose.yml
      service: postgres
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - POSTGRES_DB=appdb

  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      # Use native architecture for faster local testing
      # Comment this out if you want to test cross-architecture builds
      # platforms:
      #   - linux/amd64
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - POSTGRES_DB=appdb
      - PORT=8080
      # Enable verbose output for better debugging
      - DEBUG=true
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    # Mount only for debugging, remove for production-like test
    volumes:
      - ./backend/tmp:/app/tmp
      - ./backend/logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    external: true