# Install air : go install github.com/air-verse/air@latest

# Root directory of the project
root = "."

# Command to run the server
cmd = "./tmp/server"

# Watching for file changes
[watcher]
include = ["**/*.go"]
exclude = ["./tmp/*", "_test.go", "vendor/*", "**/generated/**"]

# Build settings
[build]
bin = "./tmp/server"                       # Binary file
cmd = "go build -o ./tmp/server server.go"
delay = 500                                # Reduced delay to 500ms for faster reloading
kill_signal = "SIGTERM"
send_interrupt = true                      # Send interrupt before kill
clean_on_exit = true                       # Clean temporary files on exit

# Logging settings
[log]
level = "info"                             # Reduced log level to info to cut down on verbose output

# Misc settings
[color]
error = "red"
warning = "yellow"
info = "blue"

[screen]
clear_on_rebuild = true                    # Clear the screen on rebuild for cleaner output
